# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\weather_app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import weather_app

class Ui_WeatherApp(object):
    def setupUi(self, WeatherApp):
        WeatherApp.setObjectName("WeatherApp")
        WeatherApp.resize(920, 517)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        WeatherApp.setFont(font)
        self.centralwidget = QtWidgets.QWidget(WeatherApp)
        self.centralwidget.setObjectName("centralwidget")

        self.location_input = QtWidgets.QLineEdit(self.centralwidget)
        self.location_input.setGeometry(QtCore.QRect(200, 50, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.location_input.setFont(font)
        self.location_input.setAlignment(QtCore.Qt.AlignCenter)
        self.location_input.setClearButtonEnabled(False)
        self.location_input.setObjectName("location_input")

        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(610, 50, 41, 41))
        self.SearchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SearchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../weather_app/images/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon)
        self.SearchButton.setObjectName("SearchButton")
        self.SearchButton.clicked.connect(self.search)

        self.currweatherlabel = QtWidgets.QLabel(self.centralwidget)
        self.currweatherlabel.setGeometry(QtCore.QRect(200, -10, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.currweatherlabel.setFont(font)
        self.currweatherlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currweatherlabel.setObjectName("currweatherlabel")

        self.templabel = QtWidgets.QLabel(self.centralwidget)
        self.templabel.setGeometry(QtCore.QRect(330, 150, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.templabel.setFont(font)
        self.templabel.setText("")
        self.templabel.setAlignment(QtCore.Qt.AlignCenter)
        self.templabel.setObjectName("templabel")

        self.feelslikelabel = QtWidgets.QLabel(self.centralwidget)
        self.feelslikelabel.setGeometry(QtCore.QRect(330, 250, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.feelslikelabel.setFont(font)
        self.feelslikelabel.setText("")
        self.feelslikelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.feelslikelabel.setObjectName("feelslikelabel")

        self.typelabel = QtWidgets.QLabel(self.centralwidget)
        self.typelabel.setGeometry(QtCore.QRect(134, 300, 551, 131))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.typelabel.setFont(font)
        self.typelabel.setText("")
        self.typelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.typelabel.setObjectName("typelabel")

        WeatherApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WeatherApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 26))
        self.menubar.setObjectName("menubar")
        WeatherApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WeatherApp)
        self.statusbar.setObjectName("statusbar")
        WeatherApp.setStatusBar(self.statusbar)

        self.retranslateUi(WeatherApp)
        QtCore.QMetaObject.connectSlotsByName(WeatherApp)

    def retranslateUi(self, WeatherApp):
        _translate = QtCore.QCoreApplication.translate
        WeatherApp.setWindowTitle(_translate("WeatherApp", "Weather App"))
        self.location_input.setStatusTip(_translate("WeatherApp", "Enter the location"))
        self.location_input.setPlaceholderText(_translate("WeatherApp", "Search Location"))
        self.currweatherlabel.setText(_translate("WeatherApp", "Current Weather"))

    def search(self):
        location = self.location_input.text().strip()
        if not location:
            self.typelabel.setText("Please enter a location!")
            return
        weather = weather_app.fetch_weather(location)
        if "error" in weather:
            self.typelabel.setText(f"Error: {weather['error']}")
        else:
            self.templabel.setText(f"{round(weather['temp'])}°C")
            self.feelslikelabel.setText(f"Feels like: {round(weather['feels_like'])}°C")
            self.typelabel.setText(weather['description'].capitalize())

            self.templabel.adjustSize()
            self.feelslikelabel.adjustSize()
            self.templabel.adjustSize()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WeatherApp = QtWidgets.QMainWindow()
    ui = Ui_WeatherApp()
    ui.setupUi(WeatherApp)
    WeatherApp.show()
    sys.exit(app.exec_())
